instructlab/training

data_process.py, main_ds.py, multipack_sampler.py, token_dataset.py, tokenizer_utils.py, utils.py
Adds all of the latest changes from @aldopareja and @fabianlim and @seshapad into the proper open-source repo.
=> Bring Training Repo into Parity with Current FSDP Repo

requirements.txt
=> fix github ref syntax

requirements.txt
=> Removes old comments

requirements.txt, src/instructlab/training/main_ds.py
=> remove omegaconf

.github/workflows/pypi.yaml
Same implementation as `sdg` and `eval`
=> Add pypi publishing automation

requirements.txt
Loosens the requirements.txt file and unpins transformers and trl
=> loosen requirements.txt

src/instructlab/training/tokenizer_utils.py, src/instructlab/training/utils.py
Past PRs were merged that broke CI jobs. Ideally this should never be
happening. Get the job back to a passing state.
Signed-off-by: Russell Bryant <rbryant@redhat.com>
=> Fix broken CI

.github/workflows/e2e.yml, .github/workflows/spellcheck.yml
Reverts instructlab/training#74
=> Revert "remove e2e for now"

src/instructlab/training/config.py, src/instructlab/training/main_ds.py
=> add missing deepspeed options

src/instructlab/training/config.py
should be an int rather than float
=> lora alpha type switch

src/instructlab/training/main_ds.py, src/instructlab/training/multipack_sampler.py
this will remove the control for sampler
- instead sampler will be decided if the max batch len cannot be found.
=> Catch Error if Packing Max Batch Len Cannot be Found

src/instructlab/training/config.py, src/instructlab/training/main_ds.py
For hardware scenarios where flash attention is potentially not supported.
(Re-implementation of now out-of-date #15)
For issue #92
=> Flash Attention Disable Toggle (Take 2)

src/instructlab/training/utils.py
Solves issue #128 
Also dependent upon: https://github.com/instructlab/GPTDolomite/pull/5
=> Fix ckpt save to include architecture for inference runtime consumption

src/instructlab/training/main_ds.py
=> Reducing deepspeed timeout to 10mins

src/instructlab/training/main_ds.py, src/instructlab/training/utils.py
Fixes issue #133 and also adds proper log streaming and saving all logs to file
=> Logging updates

src/instructlab/training/utils.py
This PR removes the `save_hf_format` function as it is not currently used anywhere. 
=> remove dead code

src/instructlab/training/chat_templates/ibm_generic_tmpl.py, src/instructlab/training/chat_templates/mistral_tmpl.py, src/instructlab/training/data_process.py
=> Updating token masking to support pretraining w/ masked special tokens

src/instructlab/training/main_ds.py, src/instructlab/training/utils.py
=> Adding weight merging for LoRA/QLoRA ckpts

src/instructlab/training/main_ds.py
Changes the verbiage and color of the success message to green. 
Fixes #155
=> Change success message at end of training

src/instructlab/training/main_ds.py
Signed-off-by: James Kunstle <jkunstle@redhat.com>
=> makes saving every save_samples an optional feature

src/instructlab/training/main_ds.py
=> fix lint error to make CI happy

.github/mergify.yml, .github/workflows/e2e-nvidia-t4-x1.yml
To align with implementation in other library repos
Note `ilab system info` is removed as that is now part of the testing script itself
=> ci: minor cleanup of E2E job

.github/workflows/e2e-nvidia-t4-x1.yml
Fixing: https://github.com/instructlab/training/actions/runs/10623800882/job/29450994348?pr=190
=> Fixing e2e to use relative path for working-directory

.github/workflows/e2e-nvidia-t4-x1.yml
Ex of error: https://github.com/instructlab/training/actions/runs/10624704122/job/29453541657?pr=192
=> Fix linting error and missing quote

.github/workflows/e2e-nvidia-t4-x1.yml
with the changes in instructlab/instructlab#2247 the CI script here needs updating
depends on instructlab/instructlab#2247
=> switch -T to -a

src/instructlab/training/data_process.py
=> Fix pretrain token list->int for masking

pyproject.toml
So that the extra is included for the published package
=> Add rocm extra to pyproject.toml

.github/workflows/e2e-nvidia-l40s-x4.yml, README.md
Missed a few in https://github.com/instructlab/training/pull/298
=> fix: add remaining missing working directory configs

tests/smoketest.sh
This commit enhances the existing bash script to encapsulate variables as "${VAR}" so that the
bounds are clearly known. For reference, see: https://google.github.io/styleguide/shellguide.html\#variable-expansion
=> enhancement: enhances bash script with proper syntax

.github/workflows/e2e-nvidia-l4-x1.yml
Adding to help with debugging space issues
=> Add disk check after tests run

src/instructlab/training/main_ds.py
Resolves: #396
We should not assign a value to this parameter, as it takes no values.
=> fix: `--keep_last_checkpoint_only` does not accept any values

README.md, examples/01_building_a_reasoning_model.ipynb
Adds the paper and about sections to the readme, and adds an examples notebook.
=> Updating README and adding reasoning SFT example

src/instructlab/training/main_ds.py
Making internal sharding strategy match the interface
=> Change default internal sharding strategy to HYBRID_SHARD

.github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/smoke.yaml, .github/workflows/unit.yaml
Signed-off-by: Oleg Silkin <97077423+RobotSail@users.noreply.github.com>
=> always log storage

.github/workflows/lint.yml, .github/workflows/smoke-py312.yaml, .github/workflows/smoke.yaml, .github/workflows/unit.yaml
=> ci: Run jobs on constraints-dev.txt change

constraints-dev.txt, requirements-dev.txt, tox.ini
=> ci: Cover more test dependencies with pins

.github/actions/run-e2e/action.yml
=> ci: Fix incorrect indent in workflow steps

.github/workflows/e2e-nvidia-l40s-x4-sdk.yml
needs pull_request_target not pull_request for access to secrets on main
=> test: fix e2e target

constraints-dev.txt, constraints-dev.txt.in
This PR updates the constraints-dev.txt file using `tox -e constraints`.
=> chore: update constraints-dev.txt (2025-06-16)

.github/workflows/e2e-nvidia-l40s-x4-sdk.yml
This reverts commit 8caf1c798e00c7d38066cb440c6769a2900325e4 and #610.
=> Revert "test: fix e2e target"

src/instructlab/training/data_process.py
This PR fixes a minor mistake in formatting a floating-point value.
=> Fix a mistake in formatting a floating-point value

constraints-dev.txt
This PR updates the constraints-dev.txt file using `tox -e constraints`.
=> chore: update constraints-dev.txt (2025-09-01)

src/instructlab/training/accelerator.py, src/instructlab/training/batch_loss_manager.py, src/instructlab/training/config.py, src/instructlab/training/data_process.py, src/instructlab/training/gpt_oss_utils_correct.py, src/instructlab/training/main_ds.py, src/instructlab/training/model.py, src/instructlab/training/padded_batch_packer.py, src/instructlab/training/sampler.py, src/instructlab/training/type_definitions.py, src/instructlab/training/utils.py, tests/unit/test_collators.py, tests/unit/test_data_process.py, tests/unit/test_padded_batch_packer.py, tests/unit/test_unmask_messages.py
This PR adds a number of improvements:
1. padded batch packer
2. refactor code so training loop is simpler
3. simplifies batch management and aggregation
4. simplifies gpt-oss saving
5. adds tests for sampler and batch packing algorithms
6. fixes gpt-oss detection during data processing
There are still a few other things to fix but this resolves the bulk of the outstanding items
=> Refactors train loop, adds padded batch packer, other fixes

requirements-cuda.txt
Adding kernels package for flash attn 3 GPT-OSS support
=> Add kernels>0.9.0 to CUDA requirements
