instructlab/training

.markdownlint-cli2.yaml

Ensure `make md-lint` works even after running `tox`. We don't want
the linter looking at anything inside the tox virtualenvs.
Signed-off-by: Russell Bryant <rbryant@redhat.com>

Make md-lint ignore the tox directory

---

requirements.txt
src/instructlab/training/main_ds.py
src/instructlab/training/utils.py

- add universal checkpointing
To verify
1. train until a `ds_native` checkpoint is saved, stop the `torchrun` process.
2. restart `torchrun` with a different `num_proc` while using the *exact same train command*, 
3. observe printouts for creating the universal checkpoint in the `latest` directory. Training will resume with the different `num_proc`
Results on Dolomite full FT
- wrong learning rate was inadvertently used here, but it does prove that the method works.
Results on Dolomite QLoRA

More Checkpointing Robustness

---

src/instructlab/training/main_ds.py
src/instructlab/training/multipack_sampler.py
src/instructlab/training/token_dataset.py
src/instructlab/training/utils.py

For non-dolomite models, packing_max_batch_len was being calculated incorrectly. This calculates the necessary increase to make sure that average batch size is similar to the specified effective_batch_size.

Multipack padding fix

---

src/instructlab/training/chat_templates/ibm_generic_tmpl.py
src/instructlab/training/chat_templates/mistral_tmpl.py
src/instructlab/training/config.py
src/instructlab/training/data_process.py
src/instructlab/training/main_ds.py
src/instructlab/training/tokenizer_utils.py
src/instructlab/training/utils.py

To support more than just the currently hard-coded IBM generic special tokens / chat template.

Adding custom chat template / special token support

---

.pylintrc
requirements.txt
src/instructlab/training/main_ds.py
src/instructlab/training/utils.py

This PR addresses #49 
This should be merged only until https://github.com/instructlab/GPTDolomite/pull/1 is merged.
- `instructlab-dolomite` has been published here https://pypi.org/project/instructlab-dolomite/.
NOTE: the branch in the `requirements.txt` needs to be switched.
Our tests show the extracted repo matches the original. 
**Updated picture** 
tested again after https://github.com/instructlab/GPTDolomite/pull/3
- see those that are tagged with `mayank`. 
- tested with both regular and universal checkpoint resumption.

Switch To InstructLab Dolomite Repo

---

src/instructlab/training/async_logger.py
src/instructlab/training/config.py
src/instructlab/training/main_ds.py
src/instructlab/training/multipack_sampler.py
src/instructlab/training/utils.py

If we specify `is_granite`, will attempt to convert a checkpoint to dolomite if during `setup_model`

Convert To Dolomite Checkpoint If Needed

---

requirements.txt

According to comments on #61, numpy 2 doesn't work with this library
right now. Instead of pinning to a specific 1.x version, allow a range
from a known working version up to, but not including 2.0.0.
Signed-off-by: Russell Bryant <rbryant@redhat.com>

requirements: Adjust numpy dependency range

---

.github/actionlint.yaml
.github/workflows/e2e.yml

This workflow runs an end-to-end test using `ilab` on a github rubber
with a single NVIDIA GPU. It will install `instructlab` from `main`
plus this library with whatever proposed changes are included in a
given PR.
Closes #63
Signed-off-by: Russell Bryant <rbryant@redhat.com>

github: Add e2e test workflow

---

src/instructlab/training/multipack_sampler.py
src/instructlab/training/utils.py

Fixes model loading on multi-gpu setups and also raises an error when batch sizes are too small for multipack sampling

Bug Fixes: Small batch barrier and Broken model loading

---

src/instructlab/training/utils.py

It will be safer to only allow a single rank to remove the directory because there is a possibility of race condition

Another Fix for Checkpointing

---

src/instructlab/training/main_ds.py
src/instructlab/training/utils.py

This PR adds the LR scheduler configuration and also fixes the granite loading issue for multinode settings.
- this PR subsumes the changes in @aldo-pareja 's `lr_scheduler` branch, so a seperate merge of that would not be necessary
- the strategy now for converting the granite checkpoint, is that each node will elect one local rank to do the convert.
- the conversion will be one on the `args.output_dir`. There is no assumption it is the same for all nodes or not.  But assuming they might be the same, the `tmpdir` is shared by a `.{group_rank}` postfix. See [group rank](https://pytorch.org/docs/stable/elastic/run.html#environment-variables)
- tested on multi node

Add LR scheduler and Fix Granite Checkpoint Loading

---

src/instructlab/training/main_ds.py
src/instructlab/training/token_dataset.py

Multipack can sometimes cause a GPU to be assigned 0 samples if the effective batch size is very small. 
- this provides an additional control `sampler`, and can be set to `"distributed"` or `"multipack"` (default)
- The `distributed` version is just a random sampler. However, we will still call `find_packing_max_batch_len_and_grad_accum` to get the `grad_accum` and `samples_per_gpu`

Add Control To Turn Off Multipack

---

src/instructlab/training/__init__.py

The `main_ds` module imports DeepSpeed and PyTorch. These imports take a very long time and slow down startup of the Instruct CLI `ilab` tool by over a second.
Use PEP 562 hooks to implement lazy import and loading for `run_training` function. The function is imported when the attribute is accessed.
See: https://github.com/instructlab/instructlab/issues/1467

Add lazy import for `run_training`

---

src/instructlab/training/__init__.py
src/instructlab/training/config.py
src/instructlab/training/main_ds.py

PR #116 added lazy loading of `run_training` function with a PEP 562 `__getattr__` module hook. Pylint does not understand the trick, which caused some problems. Replace the lazy hook with a wrapper function and deferred imports.
Also mark all public APIs with a comment, so developers are aware which classes are used by other packages.

Use deferred imports instead of lazy loading

---

src/instructlab/training/data_process.py
src/instructlab/training/token_dataset.py

We are spawning more threads than needed during data process, and using multiprocessing to get data lengths in a scenario where a single list comprehension is in almost all cases faster.

Reduce Unnecessary Multiprocessing

---

src/instructlab/training/main_ds.py

Basically the title. Just changes the logic so we dont load FusedAdam unnecessarily.

🐛: fix optimizer selection logic so that FusedAdam is never loaded when CPU offloading is enabled

---

src/instructlab/training/main_ds.py

Pydantic field is defined as `list`, but in pydantic world, it means more than just lists. E.g. it allows tuples.
https://docs.pydantic.dev/2.0/usage/types/list_types/
This patch fixes the TypeError raised from the attempt to concatenate a list with a tuple.
Related: https://github.com/instructlab/instructlab/issues/2021

Accept tuples for lora.target_modules

---

src/instructlab/training/config.py
src/instructlab/training/main_ds.py

Currently, we save checkpoints:
1. Whenever we pass enough samples, and
2. sometimes at the end of training.
This adds saving per-epoch, so one could set save_samples really high and ONLY
save at the boundary of epochs.

Adds a flag to save checkpoints at the end of an epoch

---

src/instructlab/training/data_process.py
src/instructlab/training/main_ds.py

This PR adds safeguards to prevent the following issues:
- preventing the multipack sampler from being used when it cannot adequately process all samples
- prevent empty datasets from being provided or created
- prevent `max_batch_len` from being smaller than `max_seq_len`

Provide safeguards during training

---

.github/workflows/e2e-nvidia-t4-x1.yml

This commit adds a modified version of the E2E NVIDIA T4 workflow from the instructlab/instructlab
repository to automatically test new PRs against an NVIDIA box to see how they perform end-to-end.
This PR follows up work from the following PRs:
- https://github.com/instructlab/training/pull/69
- https://github.com/instructlab/training/pull/77

feat: add e2e test for instructlab CI

---

.github/mergify.yml
.github/workflows/lint.yml

This PR adds a mergeify config that will help automate merging code into the repo and doing PRs

feat: add mergify

---

.github/workflows/e2e-nvidia-t4-x1.yml

To be consistent with new CLI change in https://github.com/instructlab/instructlab/pull/2126

ci: update runner labels to uniquely identify instance sizes

---

.github/workflows/e2e-nvidia-t4-x1.yml

right now we can see what type of runner and which repository an AWS runner is associated with, but not the associated ref and PR number
see https://github.com/instructlab/instructlab/pull/2183 for reference

ci: add AWS tags to show github ref and PR num for all jobs

---

README.md

**Description:** This PR makes small updates to the training library README
You can see the preview here as well: https://github.com/kelbrown20/kelly-training/tree/update-train-readme

Docs: Update training README

---

src/instructlab/training/main_ds.py
src/instructlab/training/utils.py

The original logic wasn't working because StreamablePopen started a process and then listened on the output file instead of returning a process that could be terminated/killed.
This adds 'process.listen' to implement the same behavior as before, but only after the StreamablePopen object has returned a reference to itself. When a KeyboardInterrupt is sent, the process can be terminated and/or killed, and the Exception/Interrupt can be raised.

changes StreamablePopen to return a process and implement listening

---

.github/workflows/stale_bot.yml

Same action as https://github.com/instructlab/instructlab/blob/main/.github/workflows/stale_bot.yml

github: add stale bot to training repo

---

.github/mergify.yml
.github/workflows/e2e-nvidia-t4-x1.yml
README.md

mergify wasn't checking markdown lint success
also changed e2e triggering criteria

fix: markdown lint error and mergify bug

---

src/instructlab/training/chat_templates/ibm_generic_tmpl.py

Currently, the expected assistant token at the end of existing msgs for generation isn't being appended, due to the condition being omitted in the chat template.
Fixes #233

Fix generic chat template saved to tokenizer for generation

---

src/instructlab/training/config.py
src/instructlab/training/main_ds.py
src/instructlab/training/utils.py

Saving and reloading for deepspeed.
Todo:

adds Accelerate full-state (opt, lr_sched, params)

---

src/instructlab/training/utils.py

This PR fixes a bug currently present in the checkpoint selection logic,
where the checkpoint names are sorted by string, e.g.:
```py
lst = ["samples_1", "samples_10","samples_19", "samples_2", "samples_9999"]
print(sorted(lst))
> ['samples_1', 'samples_10', 'samples_19', 'samples_2', 'samples_9999']
```
This PR fixes this issue by specifying the `key` parameter such that it now extracts the number at the end and uses it for comparison:
```py
sorted(lst, key=lambda x: int(x.split("_")[-1]), reverse=True)
> ['samples_9999', 'samples_19', 'samples_10', 'samples_2', 'samples_1']
```
Fixes #236 

fix: updates sorting logic to correctly compare numbers

---

Makefile
pyproject.toml
tox.ini

In the current version of the training repo, we have a few commands that help us lint
and check to see if there are any issues with types or incorrect imports. However;
there is no easy fix available when these issues are detected.
This commit introduces a few new functionalities:
1. Makefile receives 5 new commands:
- toml-lint, which lints the pyproject.toml file
- toml-fmt, which automatically formats the pyproject.toml file
- check-engine, which checks that the specified container engine ($CENGINE) is installed
- tests, which runs tests against the source repo
- fix, which fixes all fixable issues
2. The tox.ini file receives a few additions:
a. The testenv environment is defined with some preset values. Other targets are able to pull from this
b. tox -e fix is added - automatically …

fix: improve linting and automation

---

src/instructlab/training/config.py
src/instructlab/training/main_ds.py
src/instructlab/training/utils.py

In the current version of the training library, we have the default value of target_modules set to
a list oflayer names which are implementation-specific and may not reflect what a given model actually
uses for the layer names. Furthermore, the default is also a subset of all projection layers in most models,
and the recommendation is generally to use all of these layers when injecting low rank adapters.
This commit resolves that issue by introducing logic to automatically resolve the target modules
and default to using all of them when they are not provided. This commit also adds validation logic
which indicates when some of the provided modules do not exist in the model. To go a step further,
the training library will also now error out when none of the provided target modules exist in …

feat: automatically select LoRA modules when none are provided

---

.github/workflows/e2e-nvidia-t4-x1.yml

the test file name is changing in the CLI repo ergo it must be changed here as well

chore: rename 'basic-workflow-tests' to 'e2e-custom'

---

.github/mergify.yml
.github/workflows/e2e-nvidia-a10g-x1.yml
README.md

this commit adds a new E2E job meant to test integration of training library changes with the CLI's "full" train pipeline to prevent any regressions
it also updates the relevant mergify configuration

e2e: replace old small job with new medium job

---

.github/workflows/e2e-nvidia-a10g-x1.yml

was being incorrectly labeled as 'small"

fix: incorrect label for AWS medium runner

---

src/instructlab/training/main_ds.py
tox.ini

Currently, the training library does not exit when an error is encountered
within the training loop (invoked through torchrun). This commit updates
that functionality so we correctly return an exit code of 1 on child failure.
Additionally, this commit also adds the `make fix` command which
automatically fixes all trivial issues picked up on by ruff
Resolves #216

chore: add exit code & tox fix

---

.github/workflows/e2e-nvidia-a10g-x1.yml

Will fix issue with model downloads

ci: grant HF_TOKEN access to the medium-size E2E CI job

---

.github/mergify.yml
.github/workflows/e2e-nvidia-a10g-x1.yml
.github/workflows/e2e-nvidia-l40s-x4.yml

this commit adds a new workflow to the Training repo
it will run a nightly cron job to test the current 'main' branch of Training against the current 'main' branch of the CLI (instructlab)

ci: add large-size E2E CI job

---

.github/workflows/e2e-nvidia-l40s-x4.yml

https://github.com/instructlab/training/actions/runs/11485349195/job/31965270089 revealed an issue with where the `gh` command was being run - this PR ensures all of these steps are run within the checked-out `training` repo on the runner

fix: add working directory config to steps in large E2E CI job

---

.github/workflows/e2e-nvidia-a10g-x1.yml
.github/workflows/e2e-nvidia-l40s-x4.yml

This will allow us to do the following:
1. Keep the AMI consistent across all of InstructLab
2. Allow for updating the AMI without having to make a code change

ci: use org variable for AWS EC2 AMI in E2E CI jobs

---

.github/mergify.yml
.github/workflows/e2e-nvidia-l4-x1.yml
README.md

also adds '-v' to 'pip install' so we can see environmental variable info for debugging issues related to installation
Addn Context: The A10G runner was not working with the new version of VLLM we will be using - this will ensure the continuing functionality of the Medium job in this repo

ci: convert med E2E CI job to L4 GPU

---

requirements.txt
src/instructlab/training/config.py
src/instructlab/training/data_process.py
src/instructlab/training/main_ds.py
src/instructlab/training/setup_accelerator.py
src/instructlab/training/token_dataset.py
src/instructlab/training/utils.py

Updating the data collator for models with HF padding-free support, adding support for upcoming Granite HF model class, and updating flags/interface accordingly.
-Mustafa

Implementing HF Padding-Free and GraniteLM Support

---

tests/README.md
tests/smoketest.sh

During development it's convenient to be able to run full distributed training, even on a smaller dataset, just to make sure that nothing obviously fails. This will also capture support for flash attention on the machine that it's run on, and for granite models.
Also solves an inconvenience that's been annoying- testing for a given platform involves:
1. grab image with versions of dependencies for cards
2. run container
3. download and install this repo
4. write dumb versions of these scripts to run training and see if it breaks.

adds basic smoketests for main_ds and data_process CLI args

---

requirements.txt
src/instructlab/training/main_ds.py
src/instructlab/training/utils.py

Fixes bug in our collate function for HF Padding-Free, and introduces support for granite+dolomite
NOTE: Dolomite support with granite requires an additional dolomite version bump, not currently available in the instructlab-dolomite repo: https://github.com/instructlab/GPTDolomite/pull/11

Adding Dolomite Support and Bringing HF Padding-Free into Performance Parity

---

CHANGELOG.md

This PR introduces a `CHANGELOG.md` file to maintain a clear history of all changes, organized by version and type of change.
Resolves issue [#209](https://github.com/instructlab/training/issues/209) 
Signed-off-by: Lo-Mein <ryanlo5102000@gmail.com>

Documentation: Added CHANGELOG.md

---

src/instructlab/training/chat_templates/ibm_generic_tmpl.py
src/instructlab/training/chat_templates/ibm_legacy_tmpl.py
src/instructlab/training/chat_templates/mistral_tmpl.py
src/instructlab/training/chat_templates/utils.py
src/instructlab/training/tokenizer_utils.py

moves base classes used in the chat templates out of `tokenizer_utils.py` so that chat templates can be easily imported without pulling in unnecessary imports from other parts of the code

chore: move token classes into chat templates

---

src/instructlab/training/main_ds.py

Today we emit a number of important values in the logs, but we do not explicitly announce how many samples
we are planning on iterating through. This commit emits total_samples as a field in both the initial log
as well as the subsequent logs during training. This way, this value can be accessed consistently by
any program interested in displaying information about its progress for convenience.
Fixes #325

feat: add total_samples as a field to logs being emitted

---

src/instructlab/training/main_ds.py

Context Issue:
https://github.com/instructlab/training/issues/250#issue-2570104902
Implemented error handling for the import of deepspeed to prevent runtime crashes
when the module is unavailable. This improves the robustness of the application.
Issue: https://github.com/instructlab/training/issues/250

Added some safeguards when the necessary imports are not available

---

src/instructlab/training/main_ds.py

PR #291 introduced extra logic for handling DeepSpeed options selectively when we can't import specific portions, however a bug had made it through where the enum that references backends was accessing the incorrect deepspeed reference.

fix: incorrect enum selection

---

src/instructlab/training/config.py
src/instructlab/training/main_ds.py

This PR adds a bool to train_args that allows consumers to specifically request the legacy ibm template if necessary for training

feat: add toggle to pick legacy chat tmpl for granite

---

.github/workflows/e2e-nvidia-l4-x1.yml
.github/workflows/e2e-nvidia-l40s-x4.yml
requirements-dev.txt
scripts/create-loss-graph.py

Currently, the training library runs through a series of end-to-end tests which ensure there are
no bugs in the code being tested. However; we do not perform any form of validation to assure that
the training logic and quality has not diminished.
This presents an issue where we can potentially be "correct" in the sense of no hard errors being hit,
but invisible bugs may be introduced which cause models to regress in training quality, or other
bugs that plague the models themselves to seep in.
This commit fixes that problem by introducng the ability to export the training loss data itself
from the test and rendering the loss curve using matplotlib.
When the results are outputted, they can be found under the "Summary" tab of a Github actions run.
For example:
Resolves #179 
Signed-off-by: …

feat: add log exporting to e2e tests

---

.pylintrc
src/instructlab/training/main_ds.py
src/instructlab/training/setup_accelerator.py
src/instructlab/training/utils.py
tests/smoketest.sh

Currently we cannot save LoRA models with FSDP, this PR addresses this limitation by instantiating a copy of the model on CPU, loading in the LoRA settings, loading the state dict after it has been gathered, and finally performing the same save as we do elsewhere throughout the codebase. 
Resolves #241

Implement saving FSDP with LoRA

---

pyproject.toml
requirements-cuda.txt
requirements-hpu.txt
requirements-rocm.txt
requirements.txt

Adds `requirements-hpu.txt` file and `optional-dependencies.hpu` to pyproject.toml
Sets lower bound for `accelerate` for rocm, cuda, and hpu separately.
For HPU, sets `accelerate>=0.33.0` because `optimum-habana` requires this.
For CUDA/ROCm sets `accelerate=>0.34.2` because accelerate got FSDP patches that we need.

deps: change hf accelerate bound, add requirements-hpu.txt

---

.github/workflows/e2e-nvidia-l4-x1.yml

The medium training job is not currently running through the training library
and therefore does not emit the same logs. This commit disables the log exporting
logic as it is currently breaking. We intend to re-introduce this logic into CI
once the medium job is aligned with it.

fix: disable loss exporting for medium training job

---

requirements-cuda.txt
requirements-hpu.txt
requirements-rocm.txt
requirements.txt
src/instructlab/training/config.py
src/instructlab/training/setup_accelerator.py
src/instructlab/training/utils.py

Moving DeepSpeed requirement into CUDA extras, and making sure package installation is not required OOTB.

Update Dependencies to Move DeepSpeed to CUDA Extras

---

README.md

This adds a note that walks the user through the process of installing DeepSpeed with CPUAdam, including the details around ensuring that `libcurand.so` is linked correctly.

docs: include docs on installing deepspeed w/ cpuadam

---

.github/workflows/e2e-nvidia-l4-x1.yml
.github/workflows/e2e-nvidia-l40s-x4.yml
scripts/create-loss-graph.py

Resolves: https://github.com/instructlab/training/issues/359

ci: Upload phase 1 & phase 2 training logs for loss graphs

---

src/instructlab/training/data_process.py

when `"unmask": true` is included in a data sample, ensures that non-system messages are all left unmasked (special tokens still masked)

Updated token masking for new data "unmask" option (for pretraining samples)

---

.github/workflows/e2e-nvidia-l40s-x4.yml

Replaces https://github.com/instructlab/training/pull/349
Includes the changes required for our slack actions.

Adjust to slack-github-action 2.0 api changes 

---

tox.ini

We didn't have a pytest entrypoint available in our tox.ini file. This allows us to write unit tests inside the `tests` directory.
Solves: https://github.com/instructlab/training/issues/377

adds pytest to tox via `py3-unit`

---

.github/workflows/unittesting-ci-nvidia.yaml

m8g runner not available in us-east-2
Current CI broken because runner instance not available.
Signed-off-by: James Kunstle <jkunstle@redhat.com>

changes Fast unit CI runner, m8g->m7i

---

.github/workflows/e2e-nvidia-l4-x1.yml
.github/workflows/e2e-nvidia-l40s-x4.yml

This PR tackles the same issue originally identified in https://github.com/instructlab/instructlab/issues/2866, where we noticed intermittent OOM issues during some of our e2e CI jobs.
While I have not noticed any OOM issues recently in this repo, updating the default temporary write directory from `tmpfs` (aka `/tmp`) to `/home/tmp` should mitigate the risk of OOM errors occurring in our e2e CI jobs since we'll now theoretically have access to 100% of the available physical memory in our EBS volume, instead of only 50%.

chore: Change default temporary write directory in all e2e CI jobs from `tmpfs` to `/home/tmp`

---

README.md
src/instructlab/training/config.py
src/instructlab/training/main_ds.py
src/instructlab/training/utils.py

0e8605a feat: retain only last checkpoint directory
commit 0e8605a4811e66d47768cc2baee4d538ed8ad4ce
Author: Sébastien Han <seb@redhat.com>
Date:   Wed Nov 27 14:21:27 2024 +0100
feat: retain only last checkpoint directory
Introduced a new command-line argument `--keep_last_checkpoint_only`.
This flag determines whether we should only keep the last checkpoint
directory, with the previous epoch directories always being overwritten.
When this flag is enabled, the epoch directory is named `last_epoch`.
This flag is useful for managing disk space efficiently during model
training. By keeping only the last checkpoint directory and overwriting
the previous ones, it helps to significantly reduce the amount of
storage required. This is particularly beneficial when working with
large models and …

feat: retain only last checkpoint directory

---

requirements-hpu.txt

Follows-up on https://github.com/instructlab/instructlab/pull/2964

Remove optimum dependency

---

.github/workflows/unit-tests.yaml
.github/workflows/unittesting-ci-nvidia.yaml

Recreating the PR from a branch that has access to repo environment variables + secrets.

fixes unit ec2-name

---

.github/workflows/unit-tests.yaml

Uses preferred setup + permissions configuration that's standard elsewhere in our tests.

syncs unit testing workflow setup with e2e setup

---

.github/workflows/e2e-nvidia-a10g-x1.yml

Avoids more complicated changes to avoid using HF_TOKEN.

Disable medium test by default with older release branches

---

src/instructlab/training/main_ds.py

* Right now loading from local file causes the code to fail on HF checkpoints.
* This  should fix that issue

Using AutoConfig to load model config file.

---

src/instructlab/training/main_ds.py
src/instructlab/training/utils.py

Fixes logging to work in notebook environments, and also removes the existing file path barrier for huggingface models, as a follow-up to @abhi1092's PR #416 
Also now accepts any CausalLM, rather than the previous hard-coded list.

Generic notebook support

---

examples/test-dataprocess.py
processed-data/test-dataprocess.py
src/instructlab/training/config.py
src/instructlab/training/data_process.py
src/instructlab/training/main_ds.py
src/instructlab/training/tokenizer_utils.py
src/instructlab/training/type_definitions.py
src/instructlab/training/utils.py

In order to use the training library today, we need to manually define the chat template and rely on specifically parsing the special tokens.
This introduces a number of issues for consumers where other models cannot easily be used without some inital effort.
This PR resolves this issue by introducing a new form of data processing which is able to arbitrarily process data in the messages format and apply the appropriate unmasking policy.
Specifically, the new data processing script now reads the `unmask` field to determine whether to unmask all messages (aside from the system message) or just the assistant responses (skills training).
This PR adds:
- A new `process_data` API into the `data_process` module which is meant to be the main backwards-compatible user-friendly entrypoint for data …

Updates data processing logic to remove dependency on hardcoded chat templates

---

requirements-cuda.txt
src/instructlab/training/config.py
src/instructlab/training/main_ds.py
src/instructlab/training/utils.py

Liger Kernels from Linkedin Research are a drop-in performance optimization that improves training throughput by ~35% in the best case. This PR adds the option to enable the kernels for supported model architectures and should be a "free" optimization in most cases.

Adds Liger Kernels as optional optimization

---

src/instructlab/training/utils.py

Since https://github.com/huggingface/transformers/pull/36794 it handles
the return_dict with can_return_tuple decorator that expects the
argument to be passed as kwarg.
Without the patch, instructlab functional tests fail with:
AttributeError: 'bool' object has no attribute 'unsqueeze'
This is because the passed return_dict argument is incorrectly
interpreted as cache_position.
Of course, the way the model forward method is overridden here is quite
problematic and would benefit from a refactor. This patch is a stop-gap
to fix the CI with minimal changes.

fix: model.forward now accepts return_dict via kwargs

---

.github/workflows/smoke.yaml
tox.ini

Fixes tailing `unit` tests, will fix `smoke` tests when they're able to run

change pytest targets. `test-unit` and `test-smoke` to `unit` and `smoke`

---

.github/workflows/unit.yaml

pytest returned error code 5 due to zero tests found matching the
requested `fast` marker.
We are not going to mark every test with `fast` marker; unit tests are
fast by design. If they are not, it's a bug.

ci: Fix unit test run due to no tests found to execute

---

.github/workflows/unit.yaml

Unit tests are cheap and supposed to be quick and not require any
particular hardware.

ci: don't waste ec2 resources on unit tests

---

tox.ini

AFAIU we are not using them atm. We can return them if they are used in
CI.

chore: Don't install pytest dependencies for coverage reports

---

.github/workflows/unit.yaml

We no longer run these tests on EC2.

chore: Don't set ec2_runner_variant for unit tests

---

src/instructlab/training/config.py
src/instructlab/training/setup_accelerator.py

Accelerate requires mixed_precision to be passed directly in config, else the fp32 upcast gets skipped and training loses overall precision, resulting in notably worse performance. Passing this also makes our manual mixed precision policy redundant, and since we are now _actually_ using mixed precision, hybrid shard finally becomes the new default sharding strategy to keep memory expectations in parity.

Fix FSDP mixed precision setting and loss w/ accelerate

---

src/instructlab/training/main_ds.py

We change the model forward method to use a different loss function. Liger Kernel's `FusedLinearCrossEntropy` kernel doesn't materialize these logits, so our custom forward was broken for Qwen2.5, Llama3, Gemma3, etc.
This switches `FusedLinearCrossEntropy` for `FusedCrossEntropy` as the default kernel used.

fixes non-granite model instantiation with Liger Kernel

---

.github/workflows/smoke.yaml

This is to work around an issue in flash-attn build definition. The
issue manifests itself as:
```
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/tmp/pip-install-u40hct41/flash-attn_36e9333b3570426a854895a477ce846d/setup.py", line 22, in <module>
import torch
ModuleNotFoundError: No module named 'torch'
[end of output]
```
See: https://github.com/Dao-AILab/flash-attention/pull/958

ci: Install torch before flash-attn

---

.github/workflows/unit.yaml

Otherwise the tested fork with the PR on review is not validated in CI.

ci: Use pull_request as trigger for unit tests

---

.github/workflows/unit.yaml
pyproject.toml

Note: python3.13 job compiles numpy because there are no pre-built
wheels for numpy1 for this version of python. But it works nevertheless.

ci: Run unit tests for all supported python version, 3.11+

---

pyproject.toml
requirements.txt

We are not testing on older versions, and there's not a lot of reasons
to do so anyway. I believe for RHEL AI, we care about Python 3.11+ only.
For reference, https://devguide.python.org/versions/

chore: Require python3.11+

---

.github/workflows/unit.yaml

chore: don't trigger unit tests for cuda and rocm requirements changes

---

src/instructlab/training/config.py

Our default FSDPOptions object in training config was overriding the default we set in the FSDPOptions object definition.

Obey the FSDP sharding option default

---

.github/workflows/e2e-nvidia-l40s-x4.yml

This PR forces the large E2E job to leverage one of our existing CI actions that allows the CI to launch EC2 instances in different regions and availability zones if the default zone (`us-east-2b`) doesn't have availability.
Fixes:

chore: Update the large e2e job to use fallback logic for selecting EC2 instances

---

pyproject.toml
requirements-cuda.txt
requirements-deepspeed.txt

users may not want to install deepspeed when they install the cuda requirements. this moves DeepSpeed into its own requirements file so if the user wants to install DeepSpeed, they can do so with:
`pip3 install instructlab-training[cuda,deepspeed]`

moves deepspeed requirements into their own file; add deepspeed extras

---

.github/workflows/e2e-nvidia-l40s-x4.yml

For instructlab, `pip install .` does not install `vllm`, but it does install an uncapped `torch` (`2.7.0` currently).
When we install `vllm` later, we compile a binary `flash_attn` wheel against `torch-2.7.0`. `vllm-0.8.4` requires `torch==2.6.0`, so we downgrade `torch`, and then we use that with the incompatible `flash_attn` binary wheel.
To resolve this, use instructlab's `constraints-dev.txt` in the first `pip install` operation. This restricts `torch` to `2.6.0` immediately when we first install instructlab, so that we will compile `flash_attn` against that `torch` version.
Fixes: #494

use instructlab `constraints-dev.txt` in e2e test

---

.github/workflows/smoke.yaml

This is a completion of a workaround for flash-attn. The initial attempt didn't work because we still used tox to run smoke tests, which means another venv was created that did not include flash-attn.
To achieve sharing the venv for both torch installation and smoke tests, we are using tox-current-env plugin here.

ci: Use tox-current-env to reuse prepared venv with torch

---

README.md
src/instructlab/training/main_ds.py
tox.ini

extend nccl timeout to combat CI timeouts w/ FSDP optimizer state saving

fix: extend nccl timeout

---

requirements-rocm.txt

We don't need to cap these dependencies at this time. If we do, we should cap them in a `constraints-dev.txt` file like we do in the core repo, but we don't actually need a constraints file if we're not testing upstream.

deps: Remove caps on ROCm dependencies

---

.github/workflows/smoke.yaml

pull_request_target means that the workflow will be pulled from main,
not from the PR under review; so it's a waste to run the workflow in
this case.

ci: don't trigger pull_request_target job on its own workflow

---

src/instructlab/training/main_ds.py
tests/unit/test_main_ds.py

The default value is recommended, and we should not change it in
production. The knob may still be useful for debugging or testing
purposes though.

fix: Use default torch timeout for nccl watchdog unless overridden

---

src/instructlab/training/main_ds.py

non-rank-0 processes were continuing on and waiting for rank-0 forward, while rank 0 was saving artifacts. This was leading to collective timeouts. In testing, adding these barriers reduced the incidence of timeouts because non-rank-0 processes are waiting at a known wait-point.

adds barriers after checkpoint saving

---

src/instructlab/training/config.py
src/instructlab/training/data_process.py
src/instructlab/training/main_ds.py

Addresses issue #569
Enhance training configuration and logging
- Added new field `log_level` to `TrainingArgs` for improved training configuration.
- Updated `print_masked_samples` to use print statements instead of logger for better visibility during data processing.
- Integrated logging level configuration into the training setup, enabling dynamic log level adjustment.
- Fixed command construction so log level is propagated down into the training command

Logging Fixes & Enhancements

---

README.md

It was removed in 5d510fbca8b9be26c3cfee6dcf6b7f398a0d78cb.

docs: Remove badge for a no longer existing job

---

constraints-dev.txt

This PR updates the constraints-dev.txt file using `tox -e constraints`.

chore: update constraints-dev.txt (2025-05-30)

---

DCO.txt
README.md

Add the contents of https://developercertificate.org/ to `DCO.txt` at the root of this repository.
Explain to contributors that new submissions imply acceptance of the DCO.
Related: instructlab/dev-docs#192

add DCO.txt

---

.github/dependabot.yml

ci: Disable dependabot for pip dependencies

---

src/instructlab/training/config.py
src/instructlab/training/main_ds.py
src/instructlab/training/model.py
src/instructlab/training/utils.py
tests/unit/test_model.py

Introduce a new design for key components of main_ds.py. Namely splitting Model initialization, Accelerator initialization, Optimizer initialization, and Checkpoint saving initialization into classes. This commit introduces the Model class
NOTE: a follow up to this work will be to introduce classes/structure for the DataLoader, Sampler, etc. This was left out of this PR given the already large scope of change.
The Model class wraps the various AutoModel classes we support -- and aims to be a lightweight wrapper to help with usability of the library with different model types. setup_optimizer resides within the model class and returns one of the optimizer types we support
These classes are one of a few steps needed to "SDK-ify" the training library
Adding structure to code via classes can …

feat: refactor main_ds.py (1/n) Model class

---

.github/mergify.yml

We are going to disable this job for this repository and rely on contributors' implicit acceptance of `DCO.txt` instead.
Related: instructlab/dev-docs#192

ci: do not require DCO job

---

tests/smoke/test_train.py

replaces `instructlab/granite-7b-lab` with `ibm-granite/granite-3.3-2b-instruct` for smoketest so we can use smaller runner and smoketest will run faster. also adds dataset subsampling logic so we can make the testing run go arbitrarily quicker.

'granite-3.3-2b-instruct' for smoketest; smaller smoke dataset

---

requirements.txt
src/instructlab/training/main_ds.py

- **chore: bump pytorch to 2.6.0+**
- **feat: Rely on implicit detection of distributed backend**

Implicit distributed backend selection

---

.github/workflows/e2e-nvidia-l40s-x4-sdk.yml
scripts/test-data/e2e-qna-grounded-employee-skill.yaml
scripts/test-data/e2e-qna-knowledge-phoenix.yaml
scripts/test-data/profile-l40s-x4.yaml
scripts/test-sdk.sh
scripts/test_sdk.py

This CI job runs the "SDK" of training in conjunction with `ilab data generate`. The goal here is to test convergence on each PR in a timely manner

feat: add medium e2e CI job for each PR

---

.github/workflows/actionlint.yml
.github/workflows/docs.yml
.github/workflows/e2e-nvidia-l40s-x4-py312.yml
.github/workflows/e2e-nvidia-l40s-x4-sdk.yml
.github/workflows/e2e-nvidia-l40s-x4.yml
.github/workflows/lint.yml
.github/workflows/pypi.yaml
.github/workflows/smoke-py312.yaml
.github/workflows/smoke.yaml
.github/workflows/stale_bot.yml
.github/workflows/unit.yaml

No one looks at results; the value of it is unknown to anyone I asked.

ci: Remove harden-runner steps from jobs

---

README.md
docs/reasoning_content.md
src/instructlab/training/data_process.py
src/instructlab/training/type_definitions.py
tests/unit/test_data_process.py
tests/unit/test_reasoning_unmask.py
tests/unit/test_unmask_messages.py

With Qwen3, there's an edge case which can result in the unmask/mask logic breaking during data processing.
Root Cause: The error occurs specifically when using the Qwen/Qwen3-32B tokenizer, not with Qwen/Qwen2.5-32B-Instruct. The problematic sample contains multiple <think> tags in the assistant's
response.
Issue Location: The error occurs in data_process.py:555 in the unmask_messages function, where it encounters an <|UNMASK_END|> token while not in an unmasking state.
Key Findings:
1. Model-specific issue: The sample processes fine with Qwen/Qwen2.5-32B-Instruct but fails with Qwen/Qwen3-32B
2. Chat template differences: Different models have different chat templates that may tokenize the unmask tokens differently
3. Token ordering: The issue suggests that the unmask tokens are getting …

fix edge case for qwen3 data processing

---

requirements-cuda.txt

This reverts commit fdfb4fd2805298bb99aa77b427c3c519ab77643b.
This causes issues for downstream builders.
Fixes: #629

uncap accelerate in `requirements-cuda.txt`

---

constraints-dev.txt

This PR updates the constraints-dev.txt file using `tox -e constraints`.

chore: update constraints-dev.txt (2025-06-30)

---

examples/.gitignore
examples/building_a_model_with_fine-tuning_and_interpolation.ipynb
examples/interpolator.py

This tutorial aims to guide you through building a model with fine-tuning followed by interpolation.
Based on [the tutorial for building a reasoning model](examples/01_building_a_reasoning_model.ipynb), [this tutorial](examples/building_a_model_with_fine-tuning_and_interpolation.ipynb) has the minimum changes described below.
- Use granite-3.3-8b-instruct as the student model.
- Apply the pre-defined chat template for granite models.
- After fine-tuning, interpolate the last checkpoint with the original student model.

Add a tutorial for fine-tuning and interpolation

---

.github/workflows/constraints-update.yml
.github/workflows/e2e-nvidia-l40s-x4-py312.yml
.github/workflows/e2e-nvidia-l40s-x4-sdk.yml
.github/workflows/e2e-nvidia-l40s-x4.yml

Changed workflows that run automatically (on schedule) and require secrets, to only run on the main repo and not forks. 
Forks will not have the required secrets for these workflows, causing them to fail automatically. `.github/workflows/e2e-nvidia-l40s-x4-sdk.yml` doesn't run on schedule but was also updated in the same way for consistency.

Disable workflow runs on forks by default

---

requirements.txt

Bumping `numpy` cap since Numba now supports Numpy <2.3

Update numpy from <2.0 to <2.3

---

requirements-cuda.txt
requirements-rocm.txt

This PR adds the following packages to be installed as part of `instructlab-training[cuda]`:
```
uv pip install --dry-run mamba-ssm[causal-conv1d] --no-build-isolation
Resolved 44 packages in 16ms
Would download 2 packages
Would install 2 packages
+ causal-conv1d==1.5.2
+ mamba-ssm==2.2.5
```

Adds mamba-ssm[causal-conv1d] to CUDA requirements
